### ISSUE TITLE
Link to overview docs broken

### ISSUE THREAD

**Issue by paisuhas** [kata-containers/www.katacontainers.io#89] opened 2020-01-17 13:57 UTC
The following links are broken on https://katacontainers.io/community/:

https://katacontainers.io/media/uploads/katacontainers/uploads/katacontainers/kata-containers-on-boarding-deck-for-website01022018.pdf

https://katacontainers.io/media/uploads/katacontainers/uploads/katacontainers/kata_containers_overview.pdf

**Comment by grahamwhaley** [comment] 2020-01-17 14:05
Thanks for the report @paisuhas 
/cc @jimmytipit @ClaireMassey @ttx

**Comment by jimmytipit** [comment] 2020-01-17 20:17
Hi @grahamwhaley do you have the actual documents that those should link to? I don't see them in the repo.

**Comment by gcutrini** [comment] 2020-01-17 20:22
@jimmytipit you can download from https://github.com/kata-containers/www.katacontainers.io/tree/9a47a49c04034806f45d21117f9a3d157247d987/docs

**Comment by jimmytipit** [comment] 2020-01-17 20:41
Hmm. That's definitely the onboarding deck.  But if I try to link to it, I get a 404: https://katacontainers.io/docs/Kata-Containers-On-boarding-Deck-for-Website01022018.pdf

As for the overview, Claire pointed me to the doc, but it's quite out of date.  Anyone from the Kata Community want to pick that up to update?
https://docs.google.com/presentation/d/1pjJ3WwW9XvOcV34I8QGhKhK_2YGrNJtTc45RqDfspHI/edit#slide=id.gc6f73a04f_0_0

**Comment by jodh-intel** [comment] 2020-08-18 14:36
Hi @jimmytipit,

It looks like https://github.com/kata-containers/www.katacontainers.io/pull/62 removed `kata-containers-on-boarding-deck-for-website01022018.pdf`. I've extracted it from the git history and attached it below:

- [Kata-Containers-On-boarding-Deck-for-Website01022018.pdf](https://github.com/kata-containers/www.katacontainers.io/files/5090983/Kata-Containers-On-boarding-Deck-for-Website01022018.pdf)

The `kata_containers_overview.pdf` file doesn't appear to be in git which is unexpected. However, there is a version on the Wayback Machine if someone could check it is a pristine copy of the original?:

https://web.archive.org/web/20190228035118/https://katacontainers.io/media/uploads/katacontainers/uploads/katacontainers/kata_containers_overview.pdf

It would be great if we could resolve this quickly, but also if we could run some sort of checks on all links on the public site to detect issues like this automatically.

/cc @kendallnelson, @ttx.

**Comment by jimmytipit** [comment] 2020-08-18 14:58
Checking on this now.

**Comment by jimmytipit** [comment] 2020-08-18 15:01
It looks like both were moved to the docs folder: https://github.com/kata-containers/www.katacontainers.io/tree/9a47a49c04034806f45d21117f9a3d157247d987/docs

But the links aren't properly updated.  Working on it now.

**Comment by jimmytipit** [comment] 2020-08-18 15:47
ok - these are all working now.  I'll look at adding some link scanning to make sure things don't break in the future, though I don't anticipate these folders to move around again.  That was a one-time thing.

**Comment by jodh-intel** [comment] 2020-08-18 15:58
Thanks @jimmytipit. I've confirmed that going to https://katacontainers.io/community/ and clicking on the two links now works (the URLs have changed to the following fwiw):

- https://katacontainers.io/collateral/Kata-Containers-On-boarding-Deck-for-Website01022018.pdf
- https://katacontainers.io/collateral/kata-containers-1pager.pdf

Let's close this now...

**Closed by jodh-intel** 2020-08-18 15:58 UTC
Labels: bug
